build 1.2-debian:
  extends: .build
  variables:
    VERSION: "1.2-debian"
    TAGS: "${VERSION}-dev"
    #DEBUG: "true"
    RELEASE_DATE: 2018-11
    
test-1.2-debian:
  extends: .test
  variables:
    FOLDER: 1.2-debian
    VERSION: "$FOLDER"
  only:
    changes:
    - 1.2-debian/*

