build 2.0-alpine:
  extends: .build
  variables:
    FOLDER: "2.0-alpine"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev 2-dev"
    #DEBUG: "true"
    RELEASE_DATE: 2019-04

test 2.0-alpine:
  extends: .test
  variables:
    FOLDER: "2.0-alpine"
    VERSION: "$FOLDER"
  only:
    changes:
    - 2.0-alpine/*
    