build 1.0-debian:
  extends: .build
  variables:
    VERSION: "1.0-debian"
    TAGS: "${VERSION}-dev 1.0.0-debian"
    #DEBUG: "true"
    RELEASE_DATE: 2018-11
    
test-1.0-debian:
  extends: .test
  variables:
    FOLDER: 1.0-debian
    VERSION: "$FOLDER"
  only:
    changes:
    - 1.0-debian/*
