build 1.1-debian:
  extends: .build
  variables:
    VERSION: "1.1-debian"
    TAGS: "${VERSION}-dev 1.0.1-debian"
    #DEBUG: "true"
    RELEASE_DATE: 2018-11
    
test-1.1-debian:
  extends: .test
  variables:
    FOLDER: 1.1-debian
    VERSION: "$FOLDER"
  only:
    changes:
    - 1.1-debian/*

