build 1.3-debian:
  extends: .build
  variables:
    FOLDER: "1.3-debian"
    VERSION: "$FOLDER"
    TAGS: "${FOLDER}-dev 1-dev"
    #DEBUG: "true"
    RELEASE_DATE: 2019-02
    
test-1.3-debian:
  extends: .test
  variables:
    FOLDER: 1.3-debian
    VERSION: "$FOLDER"
  only:
    changes:
    - 1.3-debian/*
